spring:
  datasource:
    url: jdbc:h2:~/atb-server
    platform: h2
    username: sa
    password:
    initialization-mode: always
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 856907655562-ike5b6ec6o0slrmahiuhhtm6as4vunao.apps.googleusercontent.com
            client-secret: 5SF4n6vSiM4JayzF3RrfKeX7
            scope:
              - profile
              - email
          facebook:
            client-id: 524734651391848
            client-secret: fd353cfedb52bb27225a89062bf44210
            scope:
              - email
              - public_profile
              - picture

custom:
  oauth2:
    kakao:
      client-id: 2f5f548237c61a89a53f04539f8200cb
      scope:
        - profile

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

server:
  port: 7777